apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookinfo-zookeeper
  name: bookinfo-zookeeper
spec:
  selector:
    app: bookinfo-zookeeper
  ports:
  - port: 2181
    targetPort: 2181
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookinfo-zookeeper
  name: bookinfo-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinfo-zookeeper
  template:
    metadata:
      labels:
        app: bookinfo-zookeeper
    spec:
      containers:
      - image: library/zookeeper:3.4.13
        imagePullPolicy: IfNotPresent
        name: bookinfo-zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOO_MY_ID
          value: "1"