namespace: bookinfo

configMapGenerator:
- name: bookinfo-core-app-properties
  files:
  - ./core/application.properties
- name: bookinfo-rating-app-properties
  files:
  - ./rating/application.properties
- name: bookinfo-rating-v2-app-properties
  files:
  - ./rating/application-v2.properties
- name: bookinfo-order-app-properties
  files:
  - ./order/application.properties
- name: bookinfo-core
  envs:
  - ./core/env
- name: bookinfo-rating
  envs:
  - ./rating/env
- name: bookinfo-order
  envs:
  - ./order/env
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated

images:
- name: tmaxcloudck/bookinfo-core
  newName: core.hr.172.22.11.16.nip.io/library/bookinfo-core
  newTag: v0.0.5
- name: tmaxcloudck/bookinfo-rating-v1
  newName: core.hr.172.22.11.16.nip.io/library/bookinfo-rating
  newTag: v0.0.3
- name: tmaxcloudck/bookinfo-rating-v2
  newName: core.hr.172.22.11.16.nip.io/library/bookinfo-rating
  newTag: v0.0.5
- name: tmaxcloudck/bookinfo-order
  newName: core.hr.172.22.11.16.nip.io/library/bookinfo-order
  newTag: v0.0.5
- name: tmaxcloudck/bookinfo-db
  newName: core.hr.172.22.11.16.nip.io/library/bookinfo-db
  newTag: v0.0.5

resources:
- core/core.yaml
- rating/rating.yaml
- rating/rating-v2.yaml
- order/order.yaml
- db/postgres.yaml
- service-mesh/gateways.yaml
- service-mesh/virtual-services.yaml
- service-mesh/destination-rule.yaml
- service-mesh/service-entry.yaml