apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-rating-v2
  labels:
    app: rating
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating
      version: canary
  template:
    metadata:
      labels:
        app: rating
        version: canary
    spec:
      containers:
        - name: bookinfo-rating-v2
          image: tmaxcloudck/bookinfo-rating-v2
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: bookinfo-rating
          volumeMounts:
          - name: app-properties
            mountPath: /app/application.properties
            subPath: application-v2.properties
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
      volumes:
      - name: app-properties
        configMap:
          name: bookinfo-rating-v2-app-properties