kind: Service
apiVersion: v1
metadata:
  name: bookinfo-rating
  labels:
    name: bookinfo-rating
    service: bookinfo-rating
spec:
  selector:
    app: bookinfo-rating
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-rating-v1
  labels:
    app: bookinfo-rating
    version: v1
spec:
  selector:
    matchLabels:
      app: bookinfo-rating
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: bookinfo-rating
        version: v1
    spec:
      containers:
        - name: bookinfo-rating-v1
          image: tmaxcloudck/bookinfo-rating-v1
          imagePullPolicy: Always
          volumeMounts:
          - name: app-properties
            mountPath: /app/application.properties
            subPath: application.properties
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
      volumes:
      - name: app-properties
        configMap:
          name: bookinfo-rating-app-properties