namespace: bookinfo-ext

configMapGenerator:
- name: bookinfo-payment-app-properties
  namespace: bookinfo-ext
  files:
  - ./application.properties
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated

images:
- name: tmaxcloudck/bookinfo-payment
  newName: core.hr.172.22.11.16.nip.io/library/bookinfo-payment
  newTag: v0.0.5

resources:
- payment.yaml