kind: Service
apiVersion: v1
metadata:
  name: bookinfo-service
  labels:
    name: bookinfo-service
spec:
  ports:
    - port: 8078
      targetPort: 8078
      protocol: TCP
  selector:
    app: bookinfo-service
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-service
spec:
  selector:
    matchLabels:
      app: bookinfo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: bookinfo-service
    spec:
      containers:
        - name: bookinfo-service
          image:  tmaxcloudck/example-bookinfo:0.4.2
          ports:
            - containerPort: 8078
          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: host
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: name
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
          - name: SERVICE_NAME
            value: bookinfo-service
          - name: JAEGER_AGENT_HOST_ADDR
            value: ${JAEGER_AGENT_HOST_ADDR}
