kind: Service
apiVersion: v1
metadata:
  name: order-service
  labels:
    name: order-service
spec:
  ports:
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: order-service
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: tmaxcloudck/example-order:0.1
          ports:
            - containerPort: 8080
          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: host
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: name
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
          - name: SERVICE_NAME
            value: order-service
          - name: JAEGER_AGENT_HOST_ADDR
            value: ${JAEGER_AGENT_HOST_ADDR}
