kind: Service
apiVersion: v1
metadata:
  name: payment-service
  labels:
    name: payment-service
spec:
  ports:
    - nodePort: 30082
      port: 8079
      targetPort: 8079
      protocol: TCP
  selector:
    app: payment-service
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  selector:
    matchLabels:
      app: payment-service
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: tmaxcloudck/example-payment:0.1
          ports:
            - containerPort: 8079
          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: host
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: name
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
          - name: SERVICE_NAME
            value: payment-service
          - name: JAEGER_AGENT_HOST_ADDR
            value: ${JAEGER_AGENT_HOST_ADDR}
