version: '2.3'
services:
  core:
    image: tmaxcloudck/bookinfo-core:v0.0.3
    container_name: bookinfo-core
    volumes:
      - type: bind
        source: ./core/application.properties
        target: /app/application.properties
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    networks:
      book:
    ports:
      - 8080:8080
    depends_on:
      - postgresql
      - jaeger
  rating:
    image: tmaxcloudck/bookinfo-rating:v0.0.3
    container_name: bookinfo-rating
    volumes:
      - type: bind
        source: ./rating/application.properties
        target: /app/application.properties
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    networks:
      - book
    ports:
      - 8081:8080
    depends_on:
      - postgresql
      - jaeger
  order:
    image: tmaxcloudck/bookinfo-order:v0.0.3
    container_name: bookinfo-order
    volumes:
      - type: bind
        source: ./order/application.properties
        target: /app/application.properties
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    networks:
      - book
    ports:
      - 8082:8080
    depends_on:
      - postgresql
      - jaeger
  payment:
    image: tmaxcloudck/bookinfo-payment:v0.0.3
    container_name: bookinfo-payment
    volumes:
      - type: bind
        source: ./payment/application.properties
        target: /app/application.properties
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    networks:
      - book
    ports:
      - 8083:8080
    depends_on:
      - postgresql
      - jaeger
  postgresql:
    image: tmaxcloudck/bookinfo-db:v0.0.3
    container_name: bookinfo-db
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
#    volumes:
#      - /data/database:/var/lib/postgresql/data:z
    networks:
      book:
    ports:
      - 5432:5432
    shm_size: '1gb'
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: bookinfo-jaeger
    ports:
      - 6831:6831/udp
      - 16686:16686
    networks:
      book:
  zookeeper:
    image: bitnami/zookeeper:3.5.9
    container_name: bookinfo-zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    networks:
      book:
  kafka:
    image: bitnami/kafka:3.0.0
    container_name: bookinfo-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT= bookinfo-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      book:
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  book:
    external: false
