version: '2.3'
services:
  postgresql:
    image: tmaxcloudck/book-db:0.0.1
    container_name: book-db
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
#    volumes:
#      - /data/database:/var/lib/postgresql/data:z
    networks:
      book:
    ports:
      - 5432:5432
    shm_size: '1gb'
  core:
    image: tmaxcloudck/book-core:0.0.1
    container_name: book-core
    env_file:
      - ./core/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    networks:
      book:
    ports:
      - 8080:8080
    depends_on:
      - postgresql
  rating:
    image: tmaxcloudck/book-rating:0.0.1
    container_name: book-rating
    env_file:
      - ./rating/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    networks:
      - book
    ports:
      - 8081:8080
    depends_on:
      - postgresql

networks:
  book:
    external: false
